---
name: LovelyMusic
options:
  postGenCommand: pod install
targets:
  LovelyMusic:
    type: application
    platform: iOS
    deploymentTarget: "14.0"
    sources:
      - path: FunnyRingtones
    settings:
      base:
        CODE_SIGN_IDENTITY: iPhone Developer
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ZU88ND8437
        INFOPLIST_FILE: LovelyMusic/App/Info.plist
        DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
        ENABLE_BITCODE: 'NO'
        PRODUCT_BUNDLE_IDENTIFIER: com.meimei.LovelyMusic
        SWIFT_VERSION: 5.0
        TARGETED_DEVICE_FAMILY: 1
    sources:
      - path: LovelyMusic
        createIntermediateGroups: true
    type: application

