---
name: LovelyMusic
options:
  postGenCommand: pod install
targets:
  LovelyMusic:
    deploymentTarget: '15.0'
    platform: iOS
    preBuildScripts:
      - name: SwiftLint
        script: '"${PODS_ROOT}/SwiftLint/swiftlint" lint'
    postBuildScripts:
      - inputFiles:
          - ${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}/Contents/Resources/DWARF/${TARGET_NAME}
    settings:
      base:
        CODE_SIGN_IDENTITY: iPhone Developer
        CODE_SIGN_STYLE: Manual
        DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
        DEVELOPMENT_TEAM:
        ENABLE_BITCODE: 'NO'
        INFOPLIST_FILE: LovelyMusic/App/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.meimei.LovelyMusic
        PROVISIONING_PROFILE_SPECIFIER: Solar dev
        DEVELOPMENT_TEAM: 4ND3FKVSPM
        SWIFT_VERSION: 5.0
        TARGETED_DEVICE_FAMILY: 1
    sources:
      - path: LovelyMusic
        createIntermediateGroups: true
    type: application

